services:

  mongodb:
    image: mongo:8
    container_name: user-service-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: